[package]
name = "bridge-scrims"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.29"
tracing-subscriber = "0.3.1"

[dependencies.serenity]
version = "0.10.9"
features = ["unstable_discord_api"]

[dependencies.tokio]
version = "1.13.0"
features = ["full"]