[package]
name = "bridge-scrims"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.29"
tracing-subscriber = "0.3.1"

[dependencies.serenity]
version = "0.10.9"
default-features = false
features = ["builder", "cache", "client", "gateway", "model", "http", "utils", "unstable_discord_api", "rustls_backend"]

[dependencies.tokio]
version = "1.13.0"
features = ["full"]