
# This is the config file for general stuff
bot_token = "my token"

guild = 759894401957888031

premium_council = 803319607350788146
premium_head = 851540595155271690
prime_council = 850029321635495937
prime_head = 850037363878264912
private_council = 819766802926010378
private_head = 837741017221824532

ss_support = 774457162759012412
staff = 759949547882545154
support = 834247683484024893
trial_support = 917185016012890202

banned = 818149603475456030
support_bans = 883846880835039312
screenshare_requests = 1234567890
frozen = 1234567890
frozen_chat = 1234567890
hello_cheaters = 1234567890
ss_logs = 1234567890
freeze_emoji = 1234567890
unfreeze_emoji = 1234567890

clips = 759992463032188988
polls = 858486862212235274

# Queue channels for rolling
queue_categories = [913134187131838466, 1234, 1235]

member_count = 940907252099997747

# Prefabs
[prefabs]
discord_id = "eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjpudWxsLCJlbWJlZHMiOlt7InRpdGxlIjoiSG93IHRvIGZpbmQgaWRzIG9uIGRpc2NvcmQiLCJkZXNjcmlwdGlvbiI6IkEgZGlzY29yZCBpZCBpcyBhIHVuaXF1ZSBpZGVudGlmaWVyIGZvciBhIGNlcnRhaW4gdXNlciwgY2hhbm5lbCwgcm9sZSBvciBzZXJ2ZXIuIFdlIHVzZSB0aGlzIGlkIHRvIGRpZmZlcmVudGlhdGUgcHVuaXNobWVudHMgYW5kIG90aGVyIHVzZXIgaW5mby4gVG8gZmluZCBhIGNlcnRhaW4gaWQsIGZvbGxvdyB0aGVzZSBzdGVwcy4iLCJjb2xvciI6NTgxNDc4MywiZmllbGRzIjpbeyJuYW1lIjoiU3RlcCBPbmUiLCJ2YWx1ZSI6IkZpcnN0LCBvcGVuIHlvdXIgdXNlciBzZXR0aW5ncywgYW5kIG9wZW4gdGhlICpBZHZhbmNlZCogbWVudSwgZm91bmQgdW5kZXIgdGhlIGFwcCBzZXR0aW5ncyBzdWJoZWFkaW5nLiJ9LHsibmFtZSI6IlN0ZXAgVHdvIiwidmFsdWUiOiJUdXJuICpEZXZlbG9wZXIgTW9kZSogb24uIn0seyJuYW1lIjoiU3RlcCBUaHJlZSIsInZhbHVlIjoiUmlnaHQgY2xpY2ssIG9uIHRoZSB1c2VyLCBjaGFubmVsLCBzZXJ2ZXIgb3Igcm9sZSBvZiB3aGljaCB5b3Ugd291bGQgbGlrZSB0byBvYnRhaW4gdGhlIHJvbGUsIGFuZCBjaG9vc2UgdGhlIG9wdGlvbiAqQ29weSBJRCouIFRoaXMgc2hvdWxkIGNvcHkgdGhlIGlkIHRvIHlvdXIgZGV2aWNlIGNsaXBib2FyZCwgYW5kIGNhbiB0aGVuIGJlIHBhc3RlIHVzaW5nICpDVFJMICsgViogb24gd2luZG93cywgb3IgYW4gZXF1aXZlbGVudCBvbiBvdGhlciBvcGVyYXRpbmcgc3lzdGVtcy4ifSx7Im5hbWUiOiJGdXJ0aGVyIEhlbHAiLCJ2YWx1ZSI6IllvdSBjYW4gdXNlIFt0aGlzIHdlYnNpdGVdKGh0dHBzOi8vdGVjaHN3aWZ0Lm9yZy8yMDIwLzA0LzIyL2hvdy10by1maW5kLXlvdXItdXNlci1pZC1vbi1kaXNjb3JkLykgZm9yIGZ1cnRoZXIgZ3VpZGFuY2Ugb24gdGhlIHRvcGljLiJ9XX1dfX1dfQ"
end_of_report = "eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjpudWxsLCJlbWJlZHMiOlt7InRpdGxlIjoiRW5kIG9mIFJlcG9ydCIsImRlc2NyaXB0aW9uIjoiWW91IGhhdmUgcmVhY2hlZCB0aGUgZW5kIG9mIHRoaXMgcmVwb3J0LiBUaGlzIGRlY2lzaW9uIGlzIGZpbmFsICh3aXRoIGV2aWRlbmNlIHByZXNlbnRlZCksIGlmIHlvdSBoYXZlIGFueSB1bnJlbGF0ZWQgcXVlc3Rpb25zLCBwbGVhc2UgcmVqZWN0IHRoZSBjbG9zZSByZXF1ZXN0IGFuZCBhc2shXG5cbkhhdmUgYSBnb29kIGRheSxcblxuQnJpZGdlIFNjcmltcyBTdXBwb3J0IGFuZCBTdGFmZi4iLCJjb2xvciI6MTY3MTU3NzZ9XX19XX0"
guide = "eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjoiU2hvcnQgZ3VpZGU6IiwiZW1iZWRzIjpbeyJ0aXRsZSI6Ikd1aWRlIGZvciBcIlNraWxsXCIgUm9sZXMiLCJkZXNjcmlwdGlvbiI6IlJvbGUgb3JkZXI6XG5GaXJzdCBSb2xlOiBNZW1iZXJcblNlY29uZCBSb2xlOiBQcmltZSBcblRoaXJkIFJvbGU6IFByaXZhdGVcbkZvdXJ0aCByb2xlOiBQcmVtaXVtXG5cbllvdSBjYW4gb2J0YWluIE1lbWJlciBmcm9tIHZlcmlmeWluZy5cbllvdSBjYW4gb2J0YWluIFByaW1lIGJ5IGdldHRpbmcgdm91Y2hlcyBmcm9tIHRoZSBwcmltZSBjb3VuY2lsLCB0eXBlIHRoZSBmb2xsb3dpbmcgY29tbWFuZCB0byBzZWUgdGhlIHByaW1lIGNvdW5jaWwgYGBgL2NvdW5jaWwgcHJpbWVgYGAgRmVlbCBmcmVlIHRvIGFwcGx5IGluIDwjODUwMTE2MTY3MjEzMzgzNzEwPlxuXG5Zb3UgY2FuIG9idGFpbiBQcml2YXRlIGJ5IGdldHRpbmcgdm91Y2hlcyBmcm9tIHRoZSBwcml2YXRlIGNvdW5jaWwsIHR5cGUgdGhlIGZvbGxvd2luZyBjb21tYW5kIHRvIHNlZSB0aGUgcHJpdmF0ZSBjb3VuY2lsIGBgYC9jb3VuY2lsIHByaXZhdGVgYGAgRmVlbCBmcmVlIHRvIGFwcGx5IGluIDwjNzgxMzkyMjc5NzgzODY2MzY5PlxuXG5Zb3UgY2FuIG9idGFpbiBQcmVtaXVtIGJ5IGdldHRpbmcgdm91Y2hlcyBmcm9tIHRoZSBwcmVtaXVtIGNvdW5jaWwsIHR5cGUgdGhlIGZvbGxvd2luZyBjb21tYW5kIHRvIHNlZSB0aGUgcHJlbWl1bSBjb3VuY2lsIGBgYC9jb3VuY2lsIHByZW1pdW1gYGAgRmVlbCBmcmVlIHRvIGFwcGx5IGluIDwjNzgxMzkyMjI4NzM5ODQyMDQ4PlxuXG5JRiBZT1UgV0FOVCBNT1JFIElORk9STUFUSU9OIEFCT1VUIFRIRSBST0xFUyBBTkQgSE9XIFRPIEFQUExZIEZPUiBUSEVNIFJFQUQgPCM5MTE3MjA0MTgxMzI0OTIzNDA+IiwiY29sb3IiOjI4MTI3MDh9XX19XX0"
insufficient_evidence_cheats = "eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjpudWxsLCJlbWJlZHMiOlt7InRpdGxlIjoiX19DaGVhdHNfXyIsImRlc2NyaXB0aW9uIjoiVGhhbmtzIGZvciByZXBvcnRpbmcsIGJ1dCBzYWRseSB0aGUgZXZpZGVuY2UgeW91IHByb3ZpZGVkIHdhcyBub3QgZW5vdWdoIHRvIHB1bmlzaCB0aGVtLiBQbGVhc2Ugb3BlbiBhIFNjcmVlblNoYXJlIHRpY2tldCBuZXh0IHRpbWUgYW5kIHJlYWQgPCM4MTY3MTk0NTE4ODA5NDc3OTI+IGJlZm9yZSB5b3UgZG8gc28uIiwiY29sb3IiOm51bGx9XX19XX0"
montage = "eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjpudWxsLCJlbWJlZHMiOlt7InRpdGxlIjoiX19Nb250YWdlX18iLCJkZXNjcmlwdGlvbiI6IipOT1RFOlxuWW91IG11c3QgYmUgcHJpdmF0ZSBvciBoaWdoZXIqXG5cbjEuIHNlbmQgdGhlIHZpZGVvLiAod2Ugd2lsbCBjaGVjayBmb3IgcmFjaXNtIE5TRlcgYW5kIG90aGVyIGJhbm5hYmxlIG9mZmVuc2VzKSIsImNvbG9yIjpudWxsfV19fV19"
overlays = "eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjpudWxsLCJlbWJlZHMiOlt7InRpdGxlIjoiX19PdmVybGF5c19fIiwiZGVzY3JpcHRpb24iOiIxLk1ha2Ugc3VyZSBpdCBoYXNuJ3QgYmVlbiBwb3N0ZWQgb3IgY29waWVkLCB3ZSB3b24ndCBwb3N0IGl0IGlmIGl0J3MgY29waWVkIG9yIGFscmVhZHkgcG9zdGVkLlxuMi4gU2VuZCBhIHNjcmVlbnNob3Qgb2YgdGhlIG92ZXJsYXkuXG4zLlNlbmQgdGhlIGRvd25sb2FkIGxpbmsuICh3ZSB3aWxsIG1ha2Ugc3VyZSBpdCdzIG5vdCBhIHZpcnVzL3JhdCBzbyBkb24ndCB0cnkgaXQpIiwiY29sb3IiOm51bGx9XX19XX0"
tourney = "eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjoiUGxlYXNlIGxpc3QgdGhlIGZvbGxvd2luZyBpbmZvcm1hdGlvbiBiZWxvdyBmb3IgdXMgdG8gYWR2ZXJ0aXNlIHlvdXIgdG91cm5hbWVudC4gXG5cbi0gQmFzaWMgYWR2ZXJ0aXNlbWVudCBvZiB0aGUgdG91cm5hbWVudC4gXG4tIExpbmsgdG8gdGhlIHRvdXJuYW1lbnRcbi0gSGF2ZSBhIHByaXplIChtb25ldGFyeSBvciBub3QpIGFuZCBoYXZlIHByb29mIG9mIHRoZSBwcml6ZSIsImVtYmVkcyI6bnVsbH19XX0"
unverified = "eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjpudWxsLCJlbWJlZHMiOlt7InRpdGxlIjoiSG93IHRvIHZlcmlmeSIsImRlc2NyaXB0aW9uIjoiSGV5LCBpdCBzZWVtcyB5b3UncmUgbm90IHlldCB2ZXJpZmllZCEgVG8gdmVyaWZ5IHlvdXIgYWNjb3VudCwgaGVhZCBvdmVyIHRvIDwjODI0MzQyMjI0Mjg3OTU2OTkzPiBhbmQgcHJlc3MgdGhlIGJ1dHRvbiEgTWFrZSBzdXJlIHlvdSByZWFkIGFuZCBhZ3JlZSB0byA8Izc1OTkwMDExNzg0NjQ1ODM4OD4hIiwiY29sb3IiOjU4MTQ3ODN9XX19XX0"


[[pings]]
name = "prime"
required_role = 946614789973622805
[pings.options]
"1v1" = 948172523021926410
"2v2" = 948172550628839444

[[pings]]
name = "private"
required_role = 946614975533842493
[pings.options]
"1v1" = 948172570262396978
"2v2" = 948172610762588210

[[pings]]
name = "pack_maker"
required_role = 948178243016593469
[pings.options]
"overlay" = 948172655083794443