name: Rust CI

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        override: true

    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target aarch64-unknown-linux-gnu --verbose --release
        
    - uses: actions/upload-artifact@v3
      with:
        name: bridge-scrims
        path: target/aarch64-unknown-linux-gnu/release/bridge-scrims

    - name: Bundle Server Package
      run: |
        mkdir .package
        mv target/aarch64-unknown-linux-gnu/release/bridge-scrims .package/
        mv Config.toml .package/
        echo "${{ secrets.ENV_FILE }}" > .package/.env

    - name: Upload to Server
      uses: easingthemes/ssh-deploy@v4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: ".package/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ vars.REMOTE_TARGET }}
        SCRIPT_AFTER: |
          cd ${{ vars.REMOTE_TARGET }}
          sudo docker compose restart
