name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v3
      with:
        name: bridge-scrims
        path: target/release/bridge-scrims
      

