name: Tests

on: 
  pull_request:
  push:
    branches:
      - '!master'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Cargo Check
      run: cargo check --verbose

    - name: Cargo Test
      run: cargo test --verbose